### ISSUE TITLE
Rewrite README to fit the project, and make CI green.

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-oicq#1]
It's great to see that we have this project created!

Please make the README fit this project as the first step, so that other developers from the Wechaty community can understand what this project is, and how to use it!

And also please make the CI green.

**Comment by anaivebird** [comment]
README has been changed to fit this project, CI will be fixed soon.

**Comment by anaivebird** [comment]
CI can't become green due to QQ login QR code couldn't be scanned when CI try to run "npm run start".

**Comment by huan** [comment]
The CI should be able to turn green after #4 merged.

There are several issues in readme  need to be fixed, I hope we can fix them soon.  (For example, the npm package name is incorrect)

**Comment by anaivebird** [comment]
Several changes made on README.md, and CI has been green.

**Comment by huan** [comment]
It would be great if you can decorate the README to be more beautiful!
