### ISSUE TITLE
Prepare a live demo screen recording for the mid-term blog post

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-oicq#2]
For your mid-term blog post, please make sure to fulfill the following requirements:

1. Slides
    1. Embed a google slide version in your mid-term blog post
2. Live demo
3. Present with slides and live demo with your camera on with a zoom meeting recording video
    1. uploaded to YouTube
    2. embedded in your mid-term blog post
 4. Review your original plan, and make a new plan with the following weeks. The outcomes for each week should be defined clearly.

Please feel free to let me know if you have any questions, thank you very much.

**Comment by anaivebird** [comment]
great advice

**Comment by anaivebird** [comment]
1. Slides is on progress along with the blog
2. Done. See https://www.youtube.com/watch?v=FY4U2JPZjxE
3. Done as second point, blog will coming soon.
4. Done on middle term report and no delay on original plan.
