### ISSUE TITLE
Register a NPM account, and prepare to publish this module to NPM

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-oicq#3]
Please register an NPM account so that we can set up the CI/CD pipeline to enable DevOps with GitHub Actions.

We can do it in the next meeting of OSPP'21 project that I mentored.

After we publish the module to NPM, then the Wechaty GitHub Org can accept this repo to be transfered.

**Comment by anaivebird** [comment]
Got it, I will schedule several TODOs and make efforts to deliver all of them.

**Comment by anaivebird** [comment]
Done, results could be checked [here](https://www.npmjs.com/package/wechaty-puppet-oicq)

**Comment by huan** [comment]
That's great, good job!

Then let's continue with the following two steps:

1. Add me to the maintainers of the NPM package. (my npm account is `zixia`)
2. Please prepare to transfer this repo to the GitHub wechaty org so that we can set up better privileges with our community.

Please feel free to let me know if you have any questions.

**Comment by anaivebird** [comment]
Got it, npm invitation has been done.

**Comment by anaivebird** [comment]
The repo is on polishing preparing to be merged into Github wechaty org for our community.

**Comment by anaivebird** [comment]
It has been published to NPM. And [wechaty-getting-started](https://github.com/wechaty/wechaty-getting-started) worked with [wechaty-puppet-oicq@0.1.6](https://www.npmjs.com/package/wechaty-puppet-oicq/v/0.1.6)

![image](https://user-images.githubusercontent.com/29398611/134521819-8ab0b2d6-5351-47e2-ae02-514ba69dcd70.png)

_Originally posted by @anaivebird in https://github.com/wechaty/wechaty-puppet-oicq/issues/5#issuecomment-925848491_
